### PR TITLE
update webmock

### PR DESCRIPTION
**Pull request by seanstory**
https://github.com/elastic/crawler/pull/85 was trying to do this

#### Pre-Review Checklist
- [x] This PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `crawler.yml.example` and `elasticsearch.yml.example`)
- [x] This PR has a meaningful title
- [x] Added a label for each target release version (example: `v0.1.0`)
- [x] Ran `make notice` if any dependencies have been added

### Related Pull Requests

* generated PR (missed Gemfile change): https://github.com/elastic/crawler/pull/85

### CODE REVIEW

**Review by navarone-feekery — DISMISSED** [review]

**Comment by navarone-feekery** [comment]
@seanstory should we still merge this? I guess there's no harm

**Comment by seanstory** [comment]
Yeah, updates are generally better to have than not. And it's not even "beta" yet, so very high risk tolerance IMO

**Comment by seanstory** [comment]
We could have left renovate enabled, and just manually corrected each PR like this. Just kinda annoying.

**Comment by navarone-feekery** [comment]
> We could have left renovate enabled, and just manually corrected each PR like this. Just kinda annoying.

Renovate was also creating updates that didn't actually update, just removing `-java` suffixes from deps. So I think it's best we disabled it. ([example](https://github.com/elastic/crawler/pull/82))
We could also go through the renovate PRs that were closed and bump everything in a separate PR.

**Review by navarone-feekery — APPROVED** [review]

**Pull request merged**
