### PR TITLE
Rename fatal error to internal error

### PR DESCRIPTION
**Pull request by navarone-feekery**
Rename instances of fatal error to internal error, and add a comment description on the error init explaining what the internal error is used for.

Follow up from https://github.com/elastic/crawler/pull/63

### CODE REVIEW

**Review by artem-shelkovnikov — COMMENTED** [review]
I feel it can cause confusion with "INTERNAL_SERVER_ERROR", why not leave it as FATAL_ERROR?

**Comment by navarone-feekery** [comment]
@artem-shelkovnikov all errors are fatal to a crawl task now, so calling it fatal felt redundant. I'm open to other naming ideas.

**Comment by artem-shelkovnikov** [comment]
Hmm idk, `MISCELLANEOUS_ERROR`, `OTHER_ERROR`, `INTERNAL_CRAWLER_ERROR`?

**Comment by navarone-feekery** [comment]
@artem-shelkovnikov I went with `MISCELLANEOUS_ERROR`, thanks!

**Review by artem-shelkovnikov — APPROVED** [review]

**Pull request merged**
