### PR TITLE
added timestamps to the system logger

### PR DESCRIPTION
**Pull request by yashathwani**
## Closes https://github.com/elastic/crawler/issues/69

This pull request addresses the issue of adding timestamps to the system logger. The system logger previously did not include timestamps, making it difficult to trace and debug the logs effectively.

The current log format was [crawl_id][crawl_stage] logs here. This format has been updated to include a timestamp, resulting in a new log format of [crawl_id][crawl_stage] [timestamp] logs here. The timestamp is in ISO 8601 format, providing precise log timing, which helps in better tracking of log events.

Example of the new log output:
```
[2024-07-30T12:00:00Z][crawl:66a8f9bf1016c9206ee456a3] [primary]  Crawling site...
```

## Checklists
Pre-Review Checklist

- [ ]  This PR does NOT contain credentials of any kind, such as API keys or username/passwords (double-check crawler.yml.example and elasticsearch.yml.example)
- [ ]  This PR has a meaningful title
- [ ]  This PR links to all relevant GitHub issues that it fixes or partially addresses
- [ ] If there is no GitHub issue, please create it. Each PR should have a link to an issue
- [ ]  This PR has a thorough description
- [ ]  Covered the changes with automated tests
- [ ]  Tested the changes locally
- [ ]  Added a label for each target release version (example: v0.1.0)
- [ ]  Considered corresponding documentation changes
- [ ]  Contributed any configuration settings changes to the configuration reference
- [ ]  Ran make notice if any dependencies have been added

## Changes Requiring Extra Attention

- [ ]  Security-related changes (encryption, TLS, SSRF, etc.)
- [ ]  New external service dependencies added.

## Release Note

The system logger now includes timestamps in the log entries, enhancing traceability and debugging efficiency. The new format places the timestamp after the crawl_stage, providing clear and precise log timing for better tracking of events.

### CODE REVIEW

**Comment by navarone-feekery** [comment]
Thanks a lot for your contribution! 
Looks great so far. You can `make autocorrect` to fix any linting issues. Also don't forget to sign the contributor agreement. After that, once the CI is green, we can merge.

**Comment by yashathwani** [comment]
i have signed the agreement but it is not reflecting here in the pr could you please help how to proceed further

**Comment by navarone-feekery** [comment]
@buildkite test this

**Comment by artem-shelkovnikov** [comment]
buildkite test this

**Comment by seanstory** [comment]
@yashathwani , you win the 🥇 for being our first community contributor!
Please bear with us - we seem to have something int our Buildkite settings misconfigured so that we're struggling to run our checks on forks of our repo. We should be able to get this fixed, but we'll have to leave this PR unmerged until we do. 🙈 Thanks for helping us find and fix some rough edges!

**Comment by seanstory** [comment]
buildkite test this

**Comment by seanstory** [comment]
buildkite test this

**Comment by seanstory** [comment]
buildkite test this

**Comment by seanstory** [comment]
buildkite test this

**Comment by seanstory** [comment]
buildkite test this

**Comment by navarone-feekery** [comment]
@yashathwani I was able to run the CI manually to test your build while we figure out why it doesn't run automatically.
I don't think you can see the results, so I'll post them here:

```
rubocop
Inspecting 147 files
...W...............................................................................................................................................
Offenses:
lib/crawler/api/config.rb:389:44: W: [Correctable] Lint/UnusedBlockArgument: Unused block argument - severity. If it's necessary, use _ or _severity as an argument name to indicate that it won't be used.
        system_logger.formatter = proc do |severity, datetime, progname, msg|
                                           ^^^^^^^^
lib/crawler/api/config.rb:389:64: W: [Correctable] Lint/UnusedBlockArgument: Unused block argument - progname. If it's necessary, use _ or _progname as an argument name to indicate that it won't be used.
        system_logger.formatter = proc do |severity, datetime, progname, msg|
                                                               ^^^^^^^^
lib/crawler/api/config.rb:393:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.
147 files inspected, 3 offenses detected, 3 offenses autocorrectable
```

This can be resolved by running `make autocorrect`. Once you commit the lint fixes then I will trigger a build again for you :)

**Comment by seanstory** [comment]
buildkite test this

**Comment by navarone-feekery** [comment]
@yashathwani were you able to run `make autocorrect` to fix the linting issues?

**Comment by navarone-feekery** [comment]
@yashathwani any update on this? I'd like to get this merged. The only step remaining is to run `make autocorrect` to fix lint issues.
Let me know if you would like me to do that.

**Comment by yashathwani** [comment]
@navarone-feekery sure working on it

**Comment by navarone-feekery** [comment]
@yashathwani thanks again for the contribution. I want to merge this and it's been a while since it was updated, so I've added your changes through cherry-picking them and fixed lint. This was all handled in the PR https://github.com/elastic/crawler/pull/173
I'll close this PR now.
You'll still have credit on GitHub as a contributor, you can see it in this commit: https://github.com/elastic/crawler/commit/29512b0835ed047ec967d0a64c3aea5bf83daf2b

**Pull request closed without merging**
