### PR TITLE
Add Dockerfile.wolfi

### PR DESCRIPTION
**Pull request by navarone-feekery**
Add a wolfi version of the Dockerfile so we build from wolfi images.
The existing Dockerfile still works and is unchanged. This wolfi image will be the dockerfile we publish official images from.

### CODE REVIEW

**Review by acrewdson — COMMENTED** [review]
awesome job on getting this started 🎉 

I wonder if it could make sense to look at how the original jruby image is setting up jruby: https://github.com/jruby/docker-jruby/blob/f325c86e2c2ca0bbe82f64c0aded0719372507fa/9.4/jdk21/Dockerfile

maybe we could do something more along those lines, rather than trying to use rbenv?

**Comment by acrewdson** [comment]
> maybe we could do something more along those lines, rather than trying to use rbenv?

for fun, I did a quick test locally of the approach above and the results look promising (I just had to remove [one line](https://github.com/jruby/docker-jruby/blob/f325c86e2c2ca0bbe82f64c0aded0719372507fa/9.4/jdk21/Dockerfile#L12) and use a symlink there instead)

the resultant image has many fewer vulns than the ubuntu-based one

also I think we should examine whether we need to install [all these packages](https://github.com/elastic/crawler/pull/106/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R5); I think we may not need some of those (like `bash`); and even if we do need some of them, maybe we can use a multi-stage Dockerfile to avoid having things like `git` end up in the final image

**Comment by navarone-feekery** [comment]
@acrewdson that's really cool, thanks for doing that! Would you be able to merge in your changes to this PR? (saves me from re-doing your work)
Afterwards I can look at removing the unnecessary packages.

**Comment by acrewdson** [comment]
@navarone-feekery actually I went ahead and pushed to another branch just to avoid getting too messy https://github.com/elastic/crawler/compare/acrewdson/crawler-wolfi?expand=1

one important thing you'll need to consider is whether you want to go the route of [connectors](https://github.com/elastic/connectors) and keep two Dockerfiles in the repo: a default non-Wolfi one that can be used by anyone to build an image locally, and a Wolfi-based one that only Elastic can build (b/c the base image is not pull-able if you are unauthed) and that serves the basis for officially-published crawler images on docker.elastic.co

with that in mind, in my branch I created a `Dockerfile.wolfi` rather than modify the existing `Dockerfile`

also please note that I added some `TODO`s which we may want to address, and I'm also sure we can slim the image down, too, but I think what I have in that branch is a reasonable start that produces a working wolfi-based image

**Comment by navarone-feekery** [comment]
@acrewdson I included your changes in this PR. I decided to keep the old Dockerfile, as you mentioned it would be useful for users if they want to build the Dockerfile locally.

The only change I made to your Dockerfile.wolfi was to change the entrypoint to `/bin/bash` like it is in the original Dockerfile.

Tested and confirmed it works locally 🎉  Thanks so much!

**Review by acrewdson — APPROVED** [review]
looks good, thanks!

**Pull request merged**
